apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: example-cronjob
              envFrom:
                - configMapRef:
                    name: moc-project-config
